# creating a config map to store environment variables for the shipping application to connect to cart and mysql services.
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---

# Creating a deployment for shipping, and it will create a pod with shipping container. We set environment variables for the application to connect to cart and mysql services.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # deployment labels
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: rachelsigao/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping
---

# Creating a service to expose the shipping application on port 8080, and it will route traffic to the pods with matching labels.
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port