# Creating a deployment for the MongoDB database, which will run a single replica of the MongoDB container using the image rachelsigao/mongodb:v1.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment labels
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: rachelsigao/mongodb:v1

---

# Creating a service to expose the MongoDB database on port 27017, and it will route traffic to the pods with matching labels.
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port