# Kubernetes Deployment for MySQL database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # Labels for organizing and identifying this deployment
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  # Pod template defines what pods will be created
  template:
    metadata:
      # Pod labels - must match selector.matchLabels above
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      # ServiceAccount with permissions to read secrets
      serviceAccount: roboshop-mysql-secret-reader
      # Volumes shared between init container and main container
      volumes:
      - name: mysql-secret
        emptyDir: {}
      
      # Init container runs before main containers. It fetches MySQL password from AWS Secrets Manager. Store password in /tmp/mysql_root_password.txt
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        # Fetch secret from AWS Secrets Manager
        command:
        - sh
        - -c
        - |
          aws secretsmanager get-secret-value --secret-id roboshop/mysql/password --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
        # Mount temporary volume to share with main container
        volumeMounts:
        - mountPath: /tmp
          name: mysql-secret
      
      # Main container
      containers:
      - name: mysql
        image: rachelsigao/mysql:v2
        imagePullPolicy: Always
        # Mount volume to access password file from init container
        volumeMounts:
        - mountPath: /tmp
          name: mysql-secret
---

# Creating a service to expose the MySQL database on port 3306, and it will route traffic to the pods with matching labels.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  # Selector: routes traffic to pods with these labels
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306              # Service port (external)
    targetPort: 3306        # Container port (where MySQL listens)