# Creating a ConfigMap to store the MongoDB connection details for the catalogue service.
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

# Creating a deployment to set environment variables for the application to connect to MongoDBand creates a single replica of the catalogue service, useing the image rachelsigao/catalogue:v1.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # deployment labels
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: rachelsigao/catalogue:v1
        envFrom:
        - configMapRef:
            name: catalogue

# Creating a service to expose the catalogue application on port 8080, and it will route traffic to the pods with matching labels.
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port